### ISSUE TITLE
Stan-to-pyro transpiler?

### ISSUE THREAD

**Issue by georgewhewell** [pyro-ppl/pyro-models#10]
Hi, README mentions a stan-to-pyro compiler but github repo is 404 (https://github.com/jpchen/pyro-stan-compiler)

Has location of compiler moved or it's not available anymore?

Thanks!

**Comment by eb8680** [comment]
@georgewhewell we used the transpiler to generate the models in this repository, but I don't know that it was ever in a state suitable for use by other people and it's now very out of date with respect to the latest versions of both Pyro and Stan, so it's not actively maintained or publicly available at the moment.

If you're looking for a functioning, up-to-date Stan-to-Pyro transpiler with broad Stan feature coverage that also supports compilation to [NumPyro](https://github.com/pyro-ppl/numpyro), I recommend taking a look at [deepppl](https://github.com/deepppl/deepppl) and its [successor built directly on the new Stanc3 compiler](https://github.com/mandel/stanc3/tree/deep) by @gbdrt, @mandel and others at IBM.

**Comment by gbdrt** [comment]
Thanks @eb8680.
Sorry for the lack of documentation, I just updated the README.
https://github.com/mandel/stanc3/blob/deep/README.md

**Comment by georgewhewell** [comment]
Great, thanks both- the stanc3 fork seems to work.
